# Generated by Django 3.1.7 on 2021-03-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TextSongs', '0003_performers_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='albums',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
