# Generated by Django 3.1.7 on 2021-03-26 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TextSongs', '0006_performers_small_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=80)),
                ('album_name', models.CharField(max_length=80)),
                ('song_name', models.CharField(max_length=80)),
                ('info', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation timestamp')),
            ],
        ),
    ]
