# Generated by Django 3.1.7 on 2021-03-26 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TextSongs', '0008_auto_20210327_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertext',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
