# Generated by Django 3.1.7 on 2021-03-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TextSongs', '0009_auto_20210327_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='performers',
            name='img_slider1',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='performers',
            name='img_slider2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='performers',
            name='img_slider3',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='performers',
            name='large_text',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='performers',
            name='main_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
